platform :ios, '9.0'
use_frameworks!

target 'HackerNews_Demo' do
  # pod 'iOSLearningKit', :path => '../'
  pod 'NTExtensions', 	:path => '../'
  pod 'NTUILib',        :path => '../'
  pod 'NTFunctional', 	:path => '../'
  pod 'NTReactive',	 	:path => '../'
  pod 'NTApiClient', 	:path => '../'
  pod 'NTTesting', 		:path => '../'

  pod 'SnapKit'
  pod 'RealmSwift'

  target 'iOSLearningKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  	pod 'Nimble', '~> 5.1.1'
  end
end
