platform :ios, '9.0'
use_frameworks!

target 'HackerNews_Demo' do
  # pod 'iOSLearningKit', :path => '../'
  pod 'NTExtensions', 	:path => '../'
  pod 'NTUILib',        :path => '../'
  pod 'NTFunctional', 	:path => '../'
  pod 'NTReactive',	 	:path => '../'
  pod 'NTApiClient', 	:path => '../'
  pod 'NTTesting', 		:path => '../'

  pod 'SnapKit'
  pod 'RealmSwift'

  target 'iOSLearningKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  	pod 'Nimble', '~> 5.1.1'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == "ReactiveCocoa" then
              # There is a compilation error with ReactiveCocoa. This is a workaround
              # https://github.com/ReactiveCocoa/ReactiveCocoa/issues/3519  
              config.build_settings['SWIFT_VERSION'] = '3.2'
            else
              config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
